{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fdc97a3e-126b-400c-aff8-04aadd7af109",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import torch\n",
    "from tqdm import tqdm\n",
    "from transformers import AutoTokenizer, AutoModelForSeq2SeqLM\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c6fa3f4b-e326-4ac0-8244-8365cba6f899",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape: (80, 7)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>title</th>\n",
       "      <th>side</th>\n",
       "      <th>article_url</th>\n",
       "      <th>original_text_alternating_op</th>\n",
       "      <th>prompt</th>\n",
       "      <th>output</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>The recent Democratic presidential debate feat...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>left</td>\n",
       "      <td>Here is a summary of the articles from a left-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>right</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>identify</td>\n",
       "      <td>Democratic Primary Debate</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>A collection of post-debate commentary offers ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             model                       title  side  \\\n",
       "0  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "1  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "2  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "3  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "4    deepseek-v3p1  1st 2020 Democratic Debate  left   \n",
       "\n",
       "                                         article_url  \\\n",
       "0  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "1  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "2  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "3  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "4  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "\n",
       "                        original_text_alternating_op    prompt  \\\n",
       "0  Regarding the debate questions, \"It's hard to ...   neutral   \n",
       "1  Regarding the debate questions, \"It's hard to ...      left   \n",
       "2  Regarding the debate questions, \"It's hard to ...     right   \n",
       "3  Regarding the debate questions, \"It's hard to ...  identify   \n",
       "4  Regarding the debate questions, \"It's hard to ...   neutral   \n",
       "\n",
       "                                              output  \n",
       "0  The recent Democratic presidential debate feat...  \n",
       "1  Here is a summary of the articles from a left-...  \n",
       "2  Here is a summary of the article from a right-...  \n",
       "3                          Democratic Primary Debate  \n",
       "4  A collection of post-debate commentary offers ...  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "csv_path = r\"C:\\Users\\16248\\Desktop\\大学课程\\541 Practical Code\\summaries_output_V3__01_15_2025.csv\"\n",
    "\n",
    "df = pd.read_csv(csv_path)\n",
    "\n",
    "print(\"Shape:\", df.shape)\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "141c1766-fa7f-45a9-b6a8-d039284eb070",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape: (80, 7)\n",
      "Index(['model', 'title', 'side', 'article_url', 'original_text_alternating_op',\n",
      "       'prompt', 'output'],\n",
      "      dtype='str')\n"
     ]
    }
   ],
   "source": [
    "csv_path = r\"C:\\Users\\16248\\Desktop\\大学课程\\541 Practical Code\\summaries_output_V3__01_15_2025.csv\"\n",
    "\n",
    "df = pd.read_csv(csv_path)\n",
    "\n",
    "print(\"Shape:\", df.shape)\n",
    "df.head()\n",
    "print(df.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e49adcf4-ccb0-40d1-a7d6-c258ca8d60eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Filtered shape: (60, 7)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>prompt</th>\n",
       "      <th>output</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>neutral</td>\n",
       "      <td>The recent Democratic presidential debate feat...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>left</td>\n",
       "      <td>Here is a summary of the articles from a left-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>right</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>neutral</td>\n",
       "      <td>A collection of post-debate commentary offers ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>left</td>\n",
       "      <td>From a left-leaning perspective, the debate is...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    prompt                                             output\n",
       "0  neutral  The recent Democratic presidential debate feat...\n",
       "1     left  Here is a summary of the articles from a left-...\n",
       "2    right  Here is a summary of the article from a right-...\n",
       "4  neutral  A collection of post-debate commentary offers ...\n",
       "5     left  From a left-leaning perspective, the debate is..."
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "valid_labels = [\"left\", \"right\", \"neutral\"]\n",
    "\n",
    "df_clean = df[df[\"prompt\"].isin(valid_labels)].copy()\n",
    "\n",
    "df_clean = df_clean.dropna(subset=[\"prompt\", \"output\"])\n",
    "\n",
    "df_clean[\"prompt\"] = df_clean[\"prompt\"].str.lower().str.strip()\n",
    "df_clean[\"output\"] = df_clean[\"output\"].astype(str)\n",
    "\n",
    "print(\"Filtered shape:\", df_clean.shape)\n",
    "\n",
    "df_clean[[\"prompt\", \"output\"]].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "38bf6424-2398-4a1e-9447-b34e5939e095",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "98817184b8304531b7574b8377802951",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "config.json: 0.00B [00:00, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\huggingface_hub\\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\\Users\\16248\\.cache\\huggingface\\hub\\models--google--flan-t5-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.\n",
      "To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development\n",
      "  warnings.warn(message)\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "247e7beb1a4741f992669767396a282e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "tokenizer_config.json: 0.00B [00:00, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3a7ae7542cbb46b7ac580f2e8e12cf8e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "55ae2785e5e64ee89887ba8942a47278",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "tokenizer.json: 0.00B [00:00, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "eeec4ac9ea654f91a0babdcb51c05017",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "special_tokens_map.json: 0.00B [00:00, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "4c536ee9d7e54b74bb18243397cf3b8a",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e3b0f21b3b3e441f84e81dac33880282",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a0aa8b73fc6b42b4a4e037c747f3ca83",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using device: cpu\n"
     ]
    }
   ],
   "source": [
    "model_name = \"google/flan-t5-base\"\n",
    "\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForSeq2SeqLM.from_pretrained(model_name)\n",
    "\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "model = model.to(device)\n",
    "\n",
    "print(\"Using device:\", device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3b8d64ce-d13e-4705-a4a6-e4c2dde9a141",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_keyphrases(text):\n",
    "    prompt = f\"\"\"\n",
    "Extract short stance-related keyphrases from the following political summary.\n",
    "Focus on phrases that reveal whether the summary is left, right, or neutral.\n",
    "Return only keyphrases separated by semicolons.\n",
    "\n",
    "Summary:\n",
    "{text}\n",
    "\"\"\"\n",
    "\n",
    "    inputs = tokenizer(\n",
    "        prompt,\n",
    "        return_tensors=\"pt\",\n",
    "        truncation=True,\n",
    "        max_length=512\n",
    "    ).to(device)\n",
    "\n",
    "    outputs = model.generate(\n",
    "        **inputs,\n",
    "        max_new_tokens=80,\n",
    "        num_beams=4,\n",
    "        do_sample=False\n",
    "    )\n",
    "\n",
    "    return tokenizer.decode(outputs[0], skip_special_tokens=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "be7d0cbf-52a9-48eb-bf30-b5b94544109b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def classify_stance_from_keyphrases(keyphrases):\n",
    "    prompt = f\"\"\"\n",
    "Classify the political stance of these keyphrases.\n",
    "\n",
    "Choose exactly one label:\n",
    "left\n",
    "right\n",
    "neutral\n",
    "\n",
    "Keyphrases:\n",
    "{keyphrases}\n",
    "\n",
    "Answer with only one word.\n",
    "\"\"\"\n",
    "\n",
    "    inputs = tokenizer(\n",
    "        prompt,\n",
    "        return_tensors=\"pt\",\n",
    "        truncation=True,\n",
    "        max_length=256\n",
    "    ).to(device)\n",
    "\n",
    "    outputs = model.generate(\n",
    "        **inputs,\n",
    "        max_new_tokens=10,\n",
    "        num_beams=4,\n",
    "        do_sample=False\n",
    "    )\n",
    "\n",
    "    pred = tokenizer.decode(outputs[0], skip_special_tokens=True).lower().strip()\n",
    "\n",
    "    if \"left\" in pred:\n",
    "        return \"left\"\n",
    "    elif \"right\" in pred:\n",
    "        return \"right\"\n",
    "    elif \"neutral\" in pred:\n",
    "        return \"neutral\"\n",
    "    else:\n",
    "        return \"neutral\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "d9e088c5-6a65-44ec-986e-f6aee160fdd5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [04:49<00:00,  4.83s/it]\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>title</th>\n",
       "      <th>side</th>\n",
       "      <th>article_url</th>\n",
       "      <th>original_text_alternating_op</th>\n",
       "      <th>prompt</th>\n",
       "      <th>output</th>\n",
       "      <th>t5_keyphrases</th>\n",
       "      <th>t5_predicted_stance</th>\n",
       "      <th>correct</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>The recent Democratic presidential debate feat...</td>\n",
       "      <td>Democratic presidential debate featured a crow...</td>\n",
       "      <td>left</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>left</td>\n",
       "      <td>Here is a summary of the articles from a left-...</td>\n",
       "      <td>Democratic presidential debate highlighted the...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>right</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "      <td>Democratic presidential debate showcased the p...</td>\n",
       "      <td>left</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>A collection of post-debate commentary offers ...</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>https:/theflipside.io/archives/1st-2020-democr...</td>\n",
       "      <td>Regarding the debate questions, \"It's hard to ...</td>\n",
       "      <td>left</td>\n",
       "      <td>From a left-leaning perspective, the debate is...</td>\n",
       "      <td>left-leaning</td>\n",
       "      <td>left</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             model                       title  side  \\\n",
       "0  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "1  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "2  llama4-maverick  1st 2020 Democratic Debate  left   \n",
       "4    deepseek-v3p1  1st 2020 Democratic Debate  left   \n",
       "5    deepseek-v3p1  1st 2020 Democratic Debate  left   \n",
       "\n",
       "                                         article_url  \\\n",
       "0  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "1  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "2  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "4  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "5  https:/theflipside.io/archives/1st-2020-democr...   \n",
       "\n",
       "                        original_text_alternating_op   prompt  \\\n",
       "0  Regarding the debate questions, \"It's hard to ...  neutral   \n",
       "1  Regarding the debate questions, \"It's hard to ...     left   \n",
       "2  Regarding the debate questions, \"It's hard to ...    right   \n",
       "4  Regarding the debate questions, \"It's hard to ...  neutral   \n",
       "5  Regarding the debate questions, \"It's hard to ...     left   \n",
       "\n",
       "                                              output  \\\n",
       "0  The recent Democratic presidential debate feat...   \n",
       "1  Here is a summary of the articles from a left-...   \n",
       "2  Here is a summary of the article from a right-...   \n",
       "4  A collection of post-debate commentary offers ...   \n",
       "5  From a left-leaning perspective, the debate is...   \n",
       "\n",
       "                                       t5_keyphrases t5_predicted_stance  \\\n",
       "0  Democratic presidential debate featured a crow...                left   \n",
       "1  Democratic presidential debate highlighted the...             neutral   \n",
       "2  Democratic presidential debate showcased the p...                left   \n",
       "4                                            neutral                left   \n",
       "5                                       left-leaning                left   \n",
       "\n",
       "   correct  \n",
       "0    False  \n",
       "1    False  \n",
       "2    False  \n",
       "4    False  \n",
       "5     True  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "keyphrases_list = []\n",
    "predictions = []\n",
    "\n",
    "for text in tqdm(df_clean[\"output\"].tolist()):\n",
    "    keyphrases = generate_keyphrases(text)\n",
    "    pred = classify_stance_from_keyphrases(keyphrases)\n",
    "\n",
    "    keyphrases_list.append(keyphrases)\n",
    "    predictions.append(pred)\n",
    "\n",
    "df_clean[\"t5_keyphrases\"] = keyphrases_list\n",
    "df_clean[\"t5_predicted_stance\"] = predictions\n",
    "df_clean[\"correct\"] = df_clean[\"prompt\"] == df_clean[\"t5_predicted_stance\"]\n",
    "\n",
    "df_clean.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "65cf82a4-7437-4919-b6cb-221618bd88bf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy: 0.36666666666666664\n",
      "\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "        left     0.3396    0.9000    0.4932        20\n",
      "     neutral     0.5714    0.2000    0.2963        20\n",
      "       right     0.0000    0.0000    0.0000        20\n",
      "\n",
      "    accuracy                         0.3667        60\n",
      "   macro avg     0.3037    0.3667    0.2631        60\n",
      "weighted avg     0.3037    0.3667    0.2631        60\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n",
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n",
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n"
     ]
    }
   ],
   "source": [
    "true_labels = df_clean[\"prompt\"].tolist()\n",
    "pred_labels = df_clean[\"t5_predicted_stance\"].tolist()\n",
    "\n",
    "accuracy = accuracy_score(true_labels, pred_labels)\n",
    "\n",
    "print(\"Accuracy:\", accuracy)\n",
    "print()\n",
    "print(classification_report(true_labels, pred_labels, digits=4))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "bf41db19-fa2f-409e-baf8-1e1947509b8b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Pred left</th>\n",
       "      <th>Pred right</th>\n",
       "      <th>Pred neutral</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>True left</th>\n",
       "      <td>18</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>True right</th>\n",
       "      <td>19</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>True neutral</th>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "              Pred left  Pred right  Pred neutral\n",
       "True left            18           0             2\n",
       "True right           19           0             1\n",
       "True neutral         16           0             4"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "labels = [\"left\", \"right\", \"neutral\"]\n",
    "\n",
    "cm = confusion_matrix(true_labels, pred_labels, labels=labels)\n",
    "\n",
    "cm_df = pd.DataFrame(\n",
    "    cm,\n",
    "    index=[f\"True {label}\" for label in labels],\n",
    "    columns=[f\"Pred {label}\" for label in labels]\n",
    ")\n",
    "\n",
    "cm_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "d0fa85c9-8eba-4b38-a752-a0664362a1c1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>title</th>\n",
       "      <th>prompt</th>\n",
       "      <th>t5_predicted_stance</th>\n",
       "      <th>t5_keyphrases</th>\n",
       "      <th>output</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic presidential debate featured a crow...</td>\n",
       "      <td>The recent Democratic presidential debate feat...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>neutral</td>\n",
       "      <td>Democratic presidential debate highlighted the...</td>\n",
       "      <td>Here is a summary of the articles from a left-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic presidential debate showcased the p...</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>neutral</td>\n",
       "      <td>A collection of post-debate commentary offers ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>right-leaning</td>\n",
       "      <td>From a right-leaning perspective, the debate r...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic presidential candidates debate</td>\n",
       "      <td>The first debate among Democratic presidential...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>left</td>\n",
       "      <td>neutral</td>\n",
       "      <td>Democratic presidential debate highlighted the...</td>\n",
       "      <td>Here is a summary of the article from a left-l...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic presidential debate showcased party...</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>1st 2020 Democratic Debate</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>NBC and MSNBC shamelessly promoted Elizabeth W...</td>\n",
       "      <td>NBC and MSNBC shamelessly promoted Elizabeth W...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>partisan power grab that could lead to the und...</td>\n",
       "      <td>The inclusion of a citizenship question on the...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>The Trump administration's effort to include a...</td>\n",
       "      <td>Here is a summary of the article from a right-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>legal and political debate exists over the add...</td>\n",
       "      <td>A legal and political debate exists over the a...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>right-leaning</td>\n",
       "      <td>From a right-leaning perspective, the Trump ad...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>partisan attempt to manipulate electoral power...</td>\n",
       "      <td>The inclusion of a citizenship question on the...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>The Supreme Court is being asked to decide on ...</td>\n",
       "      <td>The Supreme Court is being asked to decide on ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>2020 Census Battle</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>right-leaning</td>\n",
       "      <td>From a right-leaning perspective, the Trump ad...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Election Update</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic presidential primary is shaping up ...</td>\n",
       "      <td>The 2020 Democratic presidential primary is sh...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>llama4-maverick</td>\n",
       "      <td>2020 Election Update</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>Democratic Party is veering sharply to the lef...</td>\n",
       "      <td>The Democratic Party is veering sharply to the...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>2020 Election Update</td>\n",
       "      <td>neutral</td>\n",
       "      <td>left</td>\n",
       "      <td>left</td>\n",
       "      <td>The text argues that the Democratic Party is m...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>deepseek-v3p1</td>\n",
       "      <td>2020 Election Update</td>\n",
       "      <td>right</td>\n",
       "      <td>left</td>\n",
       "      <td>right-leaning</td>\n",
       "      <td>From a right-leaning perspective, the Democrat...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "              model                       title   prompt t5_predicted_stance  \\\n",
       "0   llama4-maverick  1st 2020 Democratic Debate  neutral                left   \n",
       "1   llama4-maverick  1st 2020 Democratic Debate     left             neutral   \n",
       "2   llama4-maverick  1st 2020 Democratic Debate    right                left   \n",
       "4     deepseek-v3p1  1st 2020 Democratic Debate  neutral                left   \n",
       "6     deepseek-v3p1  1st 2020 Democratic Debate    right                left   \n",
       "8   llama4-maverick  1st 2020 Democratic Debate  neutral                left   \n",
       "9   llama4-maverick  1st 2020 Democratic Debate     left             neutral   \n",
       "10  llama4-maverick  1st 2020 Democratic Debate    right                left   \n",
       "14    deepseek-v3p1  1st 2020 Democratic Debate    right                left   \n",
       "16  llama4-maverick          2020 Census Battle  neutral                left   \n",
       "18  llama4-maverick          2020 Census Battle    right                left   \n",
       "20    deepseek-v3p1          2020 Census Battle  neutral                left   \n",
       "22    deepseek-v3p1          2020 Census Battle    right                left   \n",
       "24  llama4-maverick          2020 Census Battle  neutral                left   \n",
       "26  llama4-maverick          2020 Census Battle    right                left   \n",
       "30    deepseek-v3p1          2020 Census Battle    right                left   \n",
       "32  llama4-maverick        2020 Election Update  neutral                left   \n",
       "34  llama4-maverick        2020 Election Update    right                left   \n",
       "36    deepseek-v3p1        2020 Election Update  neutral                left   \n",
       "38    deepseek-v3p1        2020 Election Update    right                left   \n",
       "\n",
       "                                        t5_keyphrases  \\\n",
       "0   Democratic presidential debate featured a crow...   \n",
       "1   Democratic presidential debate highlighted the...   \n",
       "2   Democratic presidential debate showcased the p...   \n",
       "4                                             neutral   \n",
       "6                                       right-leaning   \n",
       "8           Democratic presidential candidates debate   \n",
       "9   Democratic presidential debate highlighted the...   \n",
       "10  Democratic presidential debate showcased party...   \n",
       "14  NBC and MSNBC shamelessly promoted Elizabeth W...   \n",
       "16  partisan power grab that could lead to the und...   \n",
       "18  The Trump administration's effort to include a...   \n",
       "20  legal and political debate exists over the add...   \n",
       "22                                      right-leaning   \n",
       "24  partisan attempt to manipulate electoral power...   \n",
       "26  The Supreme Court is being asked to decide on ...   \n",
       "30                                      right-leaning   \n",
       "32  Democratic presidential primary is shaping up ...   \n",
       "34  Democratic Party is veering sharply to the lef...   \n",
       "36                                               left   \n",
       "38                                      right-leaning   \n",
       "\n",
       "                                               output  \n",
       "0   The recent Democratic presidential debate feat...  \n",
       "1   Here is a summary of the articles from a left-...  \n",
       "2   Here is a summary of the article from a right-...  \n",
       "4   A collection of post-debate commentary offers ...  \n",
       "6   From a right-leaning perspective, the debate r...  \n",
       "8   The first debate among Democratic presidential...  \n",
       "9   Here is a summary of the article from a left-l...  \n",
       "10  Here is a summary of the article from a right-...  \n",
       "14  NBC and MSNBC shamelessly promoted Elizabeth W...  \n",
       "16  The inclusion of a citizenship question on the...  \n",
       "18  Here is a summary of the article from a right-...  \n",
       "20  A legal and political debate exists over the a...  \n",
       "22  From a right-leaning perspective, the Trump ad...  \n",
       "24  The inclusion of a citizenship question on the...  \n",
       "26  The Supreme Court is being asked to decide on ...  \n",
       "30  From a right-leaning perspective, the Trump ad...  \n",
       "32  The 2020 Democratic presidential primary is sh...  \n",
       "34  The Democratic Party is veering sharply to the...  \n",
       "36  The text argues that the Democratic Party is m...  \n",
       "38  From a right-leaning perspective, the Democrat...  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "wrong_cases = df_clean[df_clean[\"correct\"] == False]\n",
    "\n",
    "wrong_cases[\n",
    "    [\"model\", \"title\", \"prompt\", \"t5_predicted_stance\", \"t5_keyphrases\", \"output\"]\n",
    "].head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "04bac59a-0d54-4736-b9e7-784223baf925",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved:\n",
      "t5_keyphrase_stance_results.csv\n",
      "t5_keyphrase_stance_report.txt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n",
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n",
      "C:\\Users\\16248\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", result.shape[0])\n"
     ]
    }
   ],
   "source": [
    "df_clean.to_csv(\"t5_keyphrase_stance_results.csv\", index=False)\n",
    "\n",
    "with open(\"t5_keyphrase_stance_report.txt\", \"w\", encoding=\"utf-8\") as f:\n",
    "    f.write(f\"Accuracy: {accuracy}\\n\\n\")\n",
    "    f.write(classification_report(true_labels, pred_labels, digits=4))\n",
    "    f.write(\"\\n\\nConfusion Matrix:\\n\")\n",
    "    f.write(cm_df.to_string())\n",
    "\n",
    "print(\"Saved:\")\n",
    "print(\"t5_keyphrase_stance_results.csv\")\n",
    "print(\"t5_keyphrase_stance_report.txt\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
